### ISSUE TITLE
Crashes on launch....

### ISSUE THREAD

**Issue by catvin82** [AxolotlClient/launcher#3]
I wont provide much info in this yet (if you need more info reply and tell me what you need)
but it crashes while downloading mods on startup. 
![image](https://user-images.githubusercontent.com/96541972/193480271-523cd0e3-5075-402a-a3b1-216d9e34b46f.png)

**Comment by moehreag** [comment]
I'm sorry, but this launcher is not yet really in a usable state.. Consider using [PolyMC](https://polymc.org) for now.
If you need further assistance maybe also join the discord server [here](https://discord.gg/9Q3brQVQZN).

**Comment by catvin82** [comment]
Thanks for letting me know, I already have been using polymc and just wanted to try out your client.

**Comment by TheKodeToad** [comment]
> Thanks for letting me know, I already have been using polymc and just wanted to try out your client.

I would suggest using [Prism Launcher](https://github.com/PrismLauncher/) considering all of the things that have happened since the comment.

**Comment by moehreag** [comment]
> > Thanks for letting me know, I already have been using polymc and just wanted to try out your client.
> 
> I would suggest using [Prism Launcher](https://github.com/PrismLauncher/) considering all of the things that have happened since the comment.

yeah
